---
title: 'Final Project'
author: "Vince Birch & Stephen Polacheck 2"
date: 'Due: May 1'
output: html_notebook
---

# Front matter

```{r echo=TRUE, message=FALSE}
# always clean up R environment
rm(list = ls())

# load all packages here
library(mdsr)
library(tidyverse)
library(lubridate)
library(mosaic)
library(Hmisc)
library(dplyr)
library(Lahman)
library(rvest)
library(methods)
library(readr)
library(rpart)
library(ROCR)
library(NHANES)
library(tidyr)
library(DataComputing)
library(mosaicData)
library(tidyverse)
library(party)

```

# Loading Data

```{r}
CitiesPopulationRaw <- 
  read.csv(file = "CitiesPopulation.csv", header = TRUE, sep = ",")
CitiesEconomyRaw <- 
  read.csv(file = "CitiesEconomy.csv", header = TRUE, sep = ",")
CitiesIncomeDistributionRaw <- 
  read.csv(file = "CitiesIncomeDistribution.csv", header = TRUE, sep = ",")
CitiesEnvironmentRaw <- 
  read.csv(file = "CitiesEnvironment.csv", header = TRUE, sep = ",")
HappyCitiesRaw <- 
  read.csv(file = "HappyCities.csv", header = TRUE, sep = ",")
NFLTeamDataRaw <-
  read.csv(file = "NFL Team Data.csv", header = TRUE, sep = ",")
MLBTeamDataRaw <-
  read.csv(file = "MLBWinning.csv", header = TRUE, sep = ",")
NHLTeamDataRaw <-
  read.csv(file = "NHL Data.csv", header = TRUE, sep = ",")
NBATeamDataRaw <-
  read.csv(file = "NBAData.csv", header = TRUE, sep = ",")

```

```{r}
head(CitiesPopulationRaw, 500)
colnames(CitiesPopulationRaw)[1] <- "Country_Code"
colnames(CitiesPopulationRaw)[2] <- "City_Name"
CitiesPopulation <-
  CitiesPopulationRaw %>%
  filter(Unit.Code == "PER") %>%
  filter(Unit == "Persons") %>%
  filter(VAR == "T_T") %>%
  select(Year, City_Name, Country_Code, Value)
colnames(CitiesPopulation)[4] <- "Population"
CitiesPopulation %>%
  head(10000)
```


```{r}

colnames(CitiesEconomyRaw)[1] <- "Country_Code"
colnames(CitiesEconomyRaw)[2] <- "City_Name"
CitiesEconomy <-
  CitiesEconomyRaw %>%
  filter(VAR == "GDP_REAL_PPP") %>%
  select(Year, City_Name, Country_Code, Value)
colnames(CitiesEconomy)[4] <- "GDP"
CitiesEconomy %>%
  head(100)
```

```{r}
colnames(CitiesIncomeDistributionRaw)[1] <- "Country_Code"
colnames(CitiesIncomeDistributionRaw)[2] <- "City_Name"
CitiesIncomeDistribution <-
  CitiesIncomeDistributionRaw %>%
  filter(VAR == "INCOME_DISP_HH_REAL_PPP") %>%
  select(Year, City_Name, Country_Code, Value)
colnames(CitiesIncomeDistribution)[4] <- "IncomeDistribution"
CitiesIncomeDistribution %>%
  head(1000)
```

```{r}
colnames(CitiesEnvironmentRaw)[1] <- "Country_Code"
colnames(CitiesEnvironmentRaw)[2] <- "City_Name"
CitiesEnvironment <-
  CitiesEnvironmentRaw %>%
  select(Year, City_Name, Country_Code, Value)
colnames(CitiesEnvironment)[4] <- "SPEX_10"
CitiesEnvironment %>%
  head()
```

```{r}
colnames(HappyCitiesRaw)[1] <- "Rank"
colnames(HappyCitiesRaw)[2] <- "City"
colnames(HappyCitiesRaw)[3] <- "Total_Score"
colnames(HappyCitiesRaw)[4] <- "Emotional_Physical_WellBeing_Rank"
colnames(HappyCitiesRaw)[5] <- "Income_Employment_rank"
colnames(HappyCitiesRaw)[6] <- "Community_Environment_Rank"
HappyCities <-
  HappyCitiesRaw %>%
  select(-Rank)
head(HappyCitiesRaw, 100)
```

```{r}
head(NFLTeamDataRaw)
colnames(NFLTeamDataRaw)[1] <- "Year"
colnames(NFLTeamDataRaw)[3] <- "Team"
colnames(NFLTeamDataRaw)[4] <- "City"
colnames(NFLTeamDataRaw)[5] <- "Wins"
colnames(NFLTeamDataRaw)[6] <- "Losses"
colnames(NFLTeamDataRaw)[7] <- "Ties"
NFLTeamData <-
  NFLTeamDataRaw %>%
  select(Year, City, Team, Wins, Losses, Ties) %>%
  mutate(Year = as.numeric(Year),
         Team = gsub("[*|+]","", Team),
         Wins = as.numeric(Wins),
         Losses = as.numeric(Losses),
         Ties = as.numeric(Ties),
         Win_Percent = Wins / (Wins + Losses + Ties)) %>%
  filter(Year >= 2000)  %>%
  mutate(League = "NFL") %>%
  select(Year, City, Win_Percent, League)
head(NFLTeamData)
```
```{r}
MLBTeamWinningPercentage <-
  MLBTeamDataRaw %>%
  select(X, X2018, X2017, X2016, X2015, X2014, X2013, X2012, X2011, X2010,
         X2009, X2008, X2007, X2006, X2005, X2004, X2003, X2002, X2001, X2000) %>%
  mutate(League = "MLB")
colnames(MLBTeamWinningPercentage)[1] <- "Teams"
MLBTeamWinningPercentage %>%
  head()
```
```{r}
MLBTeamWinningPercentage2 <-
MLBTeamWinningPercentage %>%
gather("year", "WPCT", 2:21) %>%
mutate(year = gsub("X", "",year)) %>%
  mutate(league = "MLB",
         WPCT = as.numeric(WPCT),
         year = as.numeric(year)) %>%
  mutate(City = Teams)
MLBTeamWinningPercentage2 %>%
head()
```


```{r}
NBATeamWinningPercentage <-
  NBATeamDataRaw %>%
  select(Year, City, WPCT) %>%
  mutate(League = "NBA", 
         WPCT = as.numeric(WPCT))
NBATeamWinningPercentage %>%
  head()
```

```{r}
NHLTeamWinningPercentage <-
  NHLTeamDataRaw %>%
  mutate(League = "NHL") %>%
  select(Year, City, WPCT, League)
NHLTeamWinningPercentage %>%
  head()
```

```{r}
USACitiesPopulation <-
  CitiesPopulation %>%
  filter(grepl("^USA", Country_Code) == TRUE) %>%
  mutate(City_Name = gsub('\\(.*\\)', "", City_Name),
         City_Name = gsub('Tampa-Hillsborough', "Tampa", City_Name),
         City_Name = gsub('Tampa-Pinellas', "Tampa", City_Name), 
         Population = as.numeric(Population))

USACitiesPopulation
```

```{r}
USACitiesEconomy <-
  CitiesEconomy %>%
  filter(grepl("^USA", Country_Code) == TRUE) %>%
  mutate(City_Name = gsub('\\(.*\\)', "", City_Name),
         City_Name = gsub('Tampa-Hillsborough', "Tampa", City_Name),
         City_Name = gsub('Tampa-Pinellas', "Tampa", City_Name))

USACitiesEconomy %>%
  head(1000)
```

```{r}
USACitiesIncomeDistribution <-
  CitiesIncomeDistribution %>%
  filter(grepl("^USA", Country_Code) == TRUE) %>%
  mutate(City_Name = gsub('\\(.*\\)', "", City_Name),
         City_Name = gsub('Tampa-Hillsborough', "Tampa", City_Name),
         City_Name = gsub('Tampa-Pinellas', "Tampa", City_Name))

USACitiesIncomeDistribution %>%
  head(1000)
```

```{r}
USACitiesEnvironment <-
  CitiesEnvironment %>%
  filter(grepl("^USA", Country_Code) == TRUE)

USACitiesEnvironment <-
  USACitiesEnvironment %>%
  mutate(City_Name = gsub('\\(.*\\)', "", City_Name),
         City_Name = gsub('Tampa-Hillsborough', "Tampa", City_Name),
         City_Name = gsub('Tampa-Pinellas', "Tampa", City_Name))

USACitiesEnvironment %>%
  head(1000)
```

```{r}
HappyCities <-
HappyCities %>%
mutate(City = gsub(", ..", "", City), 
       Year = 2018)


```



```{r}
NFLandMLB <-
MLBTeamWinningPercentage2 %>%
  full_join(NFLTeamData, by = c("Teams" = "City", "year" = "Year"))
head(NFLandMLB, 1000)  
#head(NFLTeamData)
#head(MLBTeamWinningPercentage2)
head(NHLTeamWinningPercentage)
AddingNBA <-
NFLandMLB %>%
 full_join(NBATeamWinningPercentage, by = c("City" = "City", "year" = "Year"))

AddingNHL <-
AddingNBA %>%
 full_join(NHLTeamWinningPercentage, by = c("City" = "City", "year" = "Year"))
AddingNHL %>%
  head(1000)
```

```{r}
PlusPopulation <-
  AddingNHL %>%
 left_join(USACitiesPopulation, by = c("City" = "City_Name", "year" = "Year")) %>%
  select(-Country_Code)
```

```{r}
PlusHappy <-
  PlusPopulation %>%
 left_join(HappyCities, by = c("City" = "City"))
PlusHappy
```


```{r}

zeros <- function(wp1, wp2, wp3, wp4){
  if(is.na(wp3) == TRUE){
wp3 = 0
}
   if(is.na(wp4) == TRUE){
wp4 = 0
}
}


aggwpct <- function(data){
count = 0
winpercent = 0

wp1 = as.numeric(data[3])
wp2 = as.numeric(data[6])
wp3 = as.numeric(data[8])
wp4 = as.numeric(data[10])

if(is.na(wp1) == FALSE){
winpercent = winpercent + wp1
count = count + 1
}
if(is.na(wp2) == FALSE){
winpercent = winpercent + wp2
count = count + 1
}
if(is.na(wp3) == FALSE){
winpercent = winpercent + wp3
count = count + 1
#print(is.na(wp3) == FALSE)
}
if(is.na(wp4) == FALSE){
winpercent = winpercent + wp4
count = count + 1
}
winpercent = winpercent / count
return(winpercent)
}
```

```{r}
#do(zeros(aggwpct(PlusHappy$WPCT.x, PlusHappy$Win_Percent, PlusHappy$WPCT.y, PlusHappy$WPCT)))
 # do(aggwpct(PlusHappy$WPCT.x, PlusHappy$Win_Percent, PlusHappy$WPCT.y, PlusHappy$WPCT))

PlusHappy <-
  PlusHappy %>%
  mutate(WPCT_x = as.numeric(WPCT.x),
         Win_Percent = as.numeric(Win_Percent),
         WPCT_y = as.numeric(WPCT.y),
         WPCT = as.numeric(WPCT))

test1 <- 
  apply(PlusHappy, 1, aggwpct)
test1

PlusHappy <-
  PlusHappy %>%
  mutate(Total_WinPercent = apply(PlusHappy, 1, aggwpct))
PlusHappy
```

```{r}
PlusHappy %>%
  filter(year == 2018) %>%
ggplot(aes(x = Total_WinPercent, y = Total_Score, color = Win_Percent)) +
  geom_point() + 
  geom_jitter()
```




```{r}
NFLHappiness <-
  NFLTeamData %>%
 left_join(HappyCities, by = c("City" = "City"))

NFLHappiness

NFLHappiness %>%
  filter(Year.x == 2018) %>%
ggplot(aes(x = Win_Percent, y = Total_Score)) +
  geom_point() + 
  geom_jitter()
```






```{r}
n <- 15
SimsSmallN <- 
  mosaic::do(1000) * qdata(~ Win_Percent, p = 0.625, 
                          data = sample_n(NFLHappiness, size = n, replace = TRUE))
# inspect result
head(SimsSmallN)

favstats(~ quantile, data = SimsSmallN)

SimsSmallN %>%
  ggplot() + 
  geom_histogram(aes(x = quantile)) + 
  ggtitle("1000 simulated .625 (average quantile to get into playoffs) for WPCT among samples of n = 15")


NFLHappiness <-
  NFLHappiness %>%
  filter(Year.x == 2018)
sim1 <-
  NFLHappiness %>%
  filter(Year.x == 2018) %>%
  sample_n(size = 15, replace = TRUE)

sim1 %>%
  ggplot(aes(x = Win_Percent, y = Total_Score)) + 
  geom_point()



sim1_lm <- lm(Total_Score ~ Win_Percent, data = Sim1)
sim1_lm$coefficients


grid <- 
  grid %>%
  add_predictions(sim1_lm)

confint(lm(Total_Score ~ 1, data = sim1))

msummary(sim1_lm)


ggplot(sim1, aes(x = Win_Percent)) +
  geom_point(aes(y = Total_Score)) +
  geom_line(aes(y = pred), data = grid, colour = "red", size = 1)
```

